//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 工作流实例流转历史记录
	/// </summary>
      [Table("FlowInstanceTransitionHistory")]
    public partial class FlowInstanceTransitionHistory : Entity
    {
        
        /// <summary>
	    /// 转化时间
	    /// </summary>
         [Description("转化时间")]
        public System.DateTime CreateDate { get; set; }
        /// <summary>
	    /// 操作人Id
	    /// </summary>
         [Description("操作人Id")]
        public string CreateUserId { get; set; }
        /// <summary>
	    /// 操作人名称
	    /// </summary>
         [Description("操作人名称")]
        public string CreateUserName { get; set; }

    }
}